### ISSUE TITLE
Amazing !!!

### ISSUE THREAD

**Issue by ghost** [JohnTube/GoogleSignInForUnity#1]
thank you very much I spend so much time trying to make google sign in working !!!!

how did you do to update    .arr into the   the latest  10.2.0 version

I'm trying to get firebase authentification with your Plugin .

**Comment by JohnTube** [comment]
did you try updating the dependencies [here](https://github.com/JohnTube/GoogleSignInForUnity/blob/master/AndroidLibrary/googleplugin/build.gradle#L23)?

**Comment by ghost** [comment]
Hello , thank for you Answer  , no still having a problem .


what i did :
- Download you **github** project.
- open your  **AndroidLibrary** folder   with **android Studio** , 
- change the bundle value you ask me to change.
- Build  with android studio  . (**build / make module** google plugin)
- Delete all **.aar** on your **Unityproject/Plugin/Android**  and drag the new **googleplugin-debug.aar** under **Android/Plugin** folder and keep the manifest as it was.
- import **Firebase for Unity** into unity.
-the game build but your interaction doesn't work . (it work before all this change).

i have to delete your **.aar** because it doesn't want to compile the build .
here is the link for **Firebase SDK** 
i use only the Auth package. 
https://firebase.google.com/docs/unity/setup

i really appreciate your help .

**Comment by ghost** [comment]
after some research the problem come from firebase-auth-10.2.0.aar and play-services-auth.XXX.aar
they have containing duplicate code i'm trying to find a solution . but it's not related to your code .
you can solve the issue .  thanks.
