### ISSUE TITLE
Failed to sign in.

### ISSUE THREAD

**Issue by ItsAntiUp** [JohnTube/GoogleSignInForUnity#2]
Hello. This pugin has really helped me to create a valid Google sign in, but i can't seem to get it working. The problem is that every time i press "Sign in" on my phone, a toast message appears, saying "Failed to sign in". I don't know why is this happening so maybe someone can help me to figure this out? Thanks in advance :)

**Comment by JohnTube** [comment]
hi @TwerkyMan 
thank you for opening this issue and your kind words.
this repo is no longer useful as Google has its own now
https://github.com/googlesamples/google-signin-unity
I highly recommend you switch to it asap.
